name: "Build Docker Image"

on:
  schedule:
    - cron: "0 0 * * *" # Running 0:00 on UTC

# https://github.com/docker/build-push-action/issues/127#issuecomment-695366990
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set vars
        id: vars
        run: |
          docker build . -t test
          CURRENT_VERSION_CHROMIUM=`docker run --rm test /usr/bin/chromium-browser --version` && test $? -eq 0
          echo ${CURRENT_VERSION_CHROMIUM}
          echo "::set-output name=chrome_version::$(echo ${CURRENT_VERSION_CHROMIUM} | perl -ae 'print $F[1]')"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: alpine-chrome/alpine-chrome
          tag-sha: true
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          # tags: <org-name>/<repo-name>/<app-name>:<tag>
          tags: |
            ghcr.io/code-hex/alpine-chrome:${{ steps.vars.outputs.chrome_version }}
            ghcr.io/code-hex/alpine-chrome:latest

